server:
  # 服务端口号
  port: 8085
# LOGGING
logging:
  level:
    root: info
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/database
    username:
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000

